### PR TITLE
Dev/wabreza/fix set connection

### LINKED ISSUE #15: datasets.setAllConnections fails with connection string param
The swagger definition is incorrect and was specifying additional properties as "objects" when they should be "string".

### PR DESCRIPTION
**Pull request by wbreza**
Fixes #15

### CODE REVIEW

File: lib/autorest/operations/datasets.js [hunk 1]
```diff
@@ -1474,8 +1474,8 @@ Datasets.prototype.setAllConnections = function (collectionName, workspaceId, da
       throw new Error('parameters cannot be null or undefined and it must be of type object.');
     }
     for(var valueElement in parameters) {
```
Comment (wbreza) [inline lib/autorest/operations/datasets.js]: Regenerated from change in swagger.json

**Comment by tonyferrell** [comment]
Look's good to me.
